# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
path: "data/"
train: "images/8k/train/"
val: "images/8k/val/"

# Classes
nc: 76  # number of classes
names: [
  "regulatory--keep-right",
  "regulatory--height-limit",
  "warning--railroad-crossing-with-barriers",
  "warning--falling-rocks-or-debris-right",
  "regulatory--yield",
  "warning--curve-right",
  "regulatory--pedestrians-only",
  "warning--pedestrians-crossing",
  "regulatory--no-entry",
  "warning--slippery-road-surface",
  "warning--curve-left",
  "information--parking",
  "information--tram-bus-stop",
  "warning--crossroads",
  "regulatory--stop",
  "regulatory--maximum-speed-limit",
  "regulatory--turn-right",
  "warning--roundabout",
  "warning--road-bump",
  "warning--uneven-road",
  "warning--railroad-crossing-without-barriers",
  "regulatory--bicycles-only",
  "regulatory--yield-to-oncoming-traffic",
  "regulatory--shared-path-pedestrians-and-bicycles",
  "regulatory--no-bicycles",
  "regulatory--no-pedestrians",
  "regulatory--no-overtaking",
  "regulatory--keep-left",
  "regulatory--go-straight",
  "regulatory--no-parking",
  "regulatory--no-right-turn",
  "regulatory--no-left-turn",
  "complementary--chevron-left",
  "regulatory--no-heavy-goods-vehicles",
  "regulatory--weight-limit",
  "regulatory--no-u-turn",
  "warning--other-danger",
  "warning--junction-with-a-side-road-perpendicular-right",
  "warning--double-curve-first-right",
  "regulatory--turn-left",
  "warning--roadworks",
  "warning--children",
  "warning--traffic-merges-right",
  "warning--road-narrows-right",
  "information--motorway",
  "regulatory--pass-on-either-side",
  "warning--bicycles-crossing",
  "complementary--distance",
  "regulatory--go-straight-or-turn-right",
  "regulatory--go-straight-or-turn-left",
  "regulatory--no-motor-vehicles",
  "complementary--chevron-right",
  "information--disabled-persons",
  "regulatory--no-goods-vehicles",
  "regulatory--roundabout",
  "regulatory--no-goods-vehicles-exceeding-limit",
  "warning--traffic-signals",
  "warning--road-narrows",
  "warning--road-narrows-left",
  "information--gas-station",
  "regulatory--axel-mass-limit",
  "warning--delineator",
  "warning--wild-animals",
  "warning--domestic-animals",
  "regulatory--turn-left-or-right",
  "warning--road-slope-left",
  "warning--double-curve-first-left",
  "regulatory--no-buses",
  "warning--falling-rocks-or-debris-left",
  "warning--delineator--right",
  "warning--delineator--left",
  "warning--junction-with-a-side-road-perpendicular-left",
  "warning--road-dip",
  "warning--road-slope-right",
  "warning--traffic-merges-left",
  "information--hospital"
]  # class names
